In [6]:
%reset -f
%reload_ext autoreload
%autoreload 2
%matplotlib inline
%config Completer.use_jedi = False

In [7]:
import sys
sys.path.insert(0,"..")
from profiler import *
from utils import *
from datasets import *
from models import *
from transforms import *
import torch.nn as nn
import torch.optim as optim
import torchaudio
from torch.utils.data import Dataset, ConcatDataset
from torch.utils.data.sampler import SubsetRandomSampler
from torchvision import datasets, transforms
torchaudio.set_audio_backend('soundfile')

# Raspberry-Pi Data

In [9]:
model = DrosophilaNetRAW(outputs=2, dropout_p=.2)
optimizer = optim.Adam(model.parameters(), lr=0.001, eps=1e-3, amsgrad=True)
model, optimizer = load_checkpoint(f'{BASE_DATACREATEDDIR}/model_time_best.pth.tar', model, optimizer)
model = model.to('cuda', dtype=torch.float)

### Testing new RPi Melanogaster data 

In [10]:
dspath = "/mnt/HGST_4TB/Datasets/Fruitflies_flytrap_rpi/from_rpi/Melanogaster"

#"/home/kalfasyan/data/wingbeats/Flytrap_rpi/Backup_rpi_freeflight_20210328/20210328/wingbeats"
#44100#"/home/kalfasyan/data/wingbeats/twin_cages_experiment/sensorPi/freeflight"
#48000#"/home/kalfasyan/data/wingbeats/Flytrap_rpi/Backup_rpi_freeflight_20210328/20210402/wingbeats"
#48000#"/home/kalfasyan/data/wingbeats/Flytrap_rpi/Backup_rpi_freeflight_20210328/20210328/wingbeats"
wbpf = WingbeatDatasetProfiler(dsname=dspath, custom_label=[0], rpiformat=True)

maxpeaks = 15
minpeaks = 1
maxscore = 12
minscore = 3.5
selection = f"peaks>{minpeaks} & peaks<{maxpeaks} & score>{minscore} & score<={maxscore}"
wbpf.df = wbpf.df.query(selection)
# wbpf.plot_random_wbts()
# print(wbpf.df.shape[0])

evaluate_data(wbpf.df, model)

Found 436 in dataset: /mnt/HGST_4TB/Datasets/Fruitflies_flytrap_rpi/from_rpi/Melanogaster, and 1 label(s): ['Melanogaster']
Label(s) changed to [0]


  warnings.warn('nperseg = {0:d} is greater than input length '
/home/kalfasyan/anaconda3/envs/wbai/lib/python3.8/site-packages/scipy/signal/spectral.py:1961: UserWarning: nperseg = 5000 is greater than input length  = 4667, using nperseg = 4667
  warnings.warn('nperseg = {0:d} is greater than input length '
/home/kalfasyan/anaconda3/envs/wbai/lib/python3.8/site-packages/scipy/signal/spectral.py:1961: UserWarning: nperseg = 5000 is greater than input length  = 4667, using nperseg = 4667
  warnings.warn('nperseg = {0:d} is greater than input length '


Creating a pandas Dataframe with file-paths, clean-scores, duration, sums of abs values, indice and labels..
Duration
Sum..
Max..
Filename..
Date..
Date string..
Datehour string..
Finished.


Testing..	:  18%|█████▊                          | 2/11 [00:01<00:07,  1.19it/s]


RuntimeError: stack expects each tensor to be equal size, but got [1, 5000] at entry 0 and [1, 4667] at entry 12

### Testing new RPi Suzukii data 

In [5]:
dspath = "/home/kalfasyan/data/wingbeats/Suzukii_Rpi_converted_wingbeats"

#"/home/kalfasyan/data/wingbeats/Flytrap_rpi/Backup_rpi_freeflight_20210328/20210328/wingbeats"
#44100#"/home/kalfasyan/data/wingbeats/twin_cages_experiment/sensorPi/freeflight"
#48000#"/home/kalfasyan/data/wingbeats/Flytrap_rpi/Backup_rpi_freeflight_20210328/20210402/wingbeats"
#48000#"/home/kalfasyan/data/wingbeats/Flytrap_rpi/Backup_rpi_freeflight_20210328/20210328/wingbeats"
wbpf = WingbeatDatasetProfiler(dsname=dspath, custom_label=[1], rpiformat=True)

maxpeaks = 15
minpeaks = 1
maxscore = 12
minscore = 3.5
selection = f"peaks>{minpeaks} & peaks<{maxpeaks} & score>{minscore} & score<={maxscore}"
wbpf.df = wbpf.df.query(selection)
# wbpf.plot_random_wbts()
# print(wbpf.df.shape[0])

evaluate_data(wbpf.df, model)

Found 128 in dataset: /home/kalfasyan/data/wingbeats/Suzukii_Rpi_converted_wingbeats, and 128 label(s): ['20210328_191917_Tna_Hna.wav' '20210328_192456_Tna_Hna.wav'
 '20210328_192553_Tna_Hna.wav' '20210328_192714_Tna_Hna.wav'
 '20210328_193045_Tna_Hna.wav' '20210328_193643_Tna_Hna.wav'
 '20210328_193734_Tna_Hna.wav' '20210328_193908_Tna_Hna.wav'
 '20210328_194951_Tna_Hna.wav' '20210328_195121_Tna_Hna.wav'
 '20210328_195317_Tna_Hna.wav' '20210328_195811_Tna_Hna.wav'
 '20210328_195835_Tna_Hna.wav' '20210328_200848_Tna_Hna.wav'
 '20210328_202817_Tna_Hna.wav' '20210328_205127_Tna_Hna.wav'
 '20210328_205735_Tna_Hna.wav' '20210328_205756_Tna_Hna.wav'
 '20210328_210203_Tna_Hna.wav' '20210328_210238_Tna_Hna.wav'
 '20210328_210505_Tna_Hna.wav' '20210328_211812_Tna_Hna.wav'
 '20210328_212342_Tna_Hna.wav' '20210328_213208_Tna_Hna.wav'
 '20210328_213249_Tna_Hna.wav' '20210328_213311_Tna_Hna.wav'
 '20210328_213808_Tna_Hna.wav' '20210328_214018_Tna_Hna.wav'
 '20210328_214208_Tna_Hna.wav' '20210328_2

Testing..	:   0%|          | 0/4 [00:00<?, ?it/s]

Creating a pandas Dataframe with file-paths, clean-scores, duration, sums of abs values, indice and labels..
Finished.


Testing..	: 100%|██████████| 4/4 [00:00<00:00, 22.29it/s]

Accuracy: 98.31
Balanced accuracy: 98.31
Confusion matrix: 
[[0.         0.        ]
 [0.01694915 0.98305085]]
1    116
0      2
dtype: int64



/home/kalfasyan/anaconda3/envs/wbai/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1850: UserWarning: y_pred contains classes not in y_true
  warnings.warn('y_pred contains classes not in y_true')


# SD card data

In [6]:
%reset -f
%reload_ext autoreload
%autoreload 2
%matplotlib inline
%config Completer.use_jedi = False

In [7]:
import sys
sys.path.insert(0,"..")
from profiler import *
from utils import *
from datasets import *
from models import *
from transforms import *
import torch.nn as nn
import torch.optim as optim
import torchaudio
from torch.utils.data import Dataset, ConcatDataset
from torch.utils.data.sampler import SubsetRandomSampler
from torchvision import datasets, transforms
torchaudio.set_audio_backend('soundfile')

transforms_list_test = [Bandpass(lowcut=140, highcut=1500)]
BASE_DATACREATEDDIR

Path('/home/kalfasyan/projects/wbai/data_created')

In [8]:
model = DrosophilaNetRAW(outputs=2, dropout_p=.2)
optimizer = optim.Adam(model.parameters(), lr=0.001, eps=1e-3, amsgrad=True)
model, optimizer = load_checkpoint(f'{BASE_DATACREATEDDIR}/model_time_best.pth.tar', model, optimizer)
model = model.to('cuda', dtype=torch.float)

### Testing with new SD card data - Melanogasters

In [9]:
dspath = "/home/kalfasyan/data/wingbeats/wingbeats_20211129/wingbeats_correct_dates/Melanogaster_202111_SD"
wbpf = WingbeatDatasetProfiler(dsname=dspath, custom_label=[0], rpiformat=False)

maxpeaks = 15
minpeaks = 1
maxscore = 12
minscore = 3.5
selection = f"peaks>{minpeaks} & peaks<{maxpeaks} & score>{minscore} & score<={maxscore}"
wbpf.df = wbpf.df.query(selection)

evaluate_data(wbpf.df, model, batch_size=8, transforms_list=transforms_list_test)

Found 11136 in dataset: /home/kalfasyan/data/wingbeats/wingbeats_20211129/wingbeats_correct_dates/Melanogaster_202111_SD, and 1 label(s): ['wingbeats_correct_dates']
Label(s) changed to [0]


Creating a pandas Dataframe with file-paths, clean-scores, duration, sums of abs values, indice and labels..
Finished.


Testing..	: 100%|██████████| 740/740 [00:07<00:00, 95.03it/s] 

Accuracy: 63.13
Balanced accuracy: 63.13
Confusion matrix: 
[[0.63129436 0.36870564]
 [0.         0.        ]]
0    3736
1    2182
dtype: int64



/home/kalfasyan/anaconda3/envs/wbai/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1850: UserWarning: y_pred contains classes not in y_true
  warnings.warn('y_pred contains classes not in y_true')


### Testing with new SD card data - Suzukiis

In [11]:
dspath = "/home/kalfasyan/data/wingbeats/wingbeats_20211129/wingbeats_correct_dates/Suzukii_202111_SD/"
wbpf = WingbeatDatasetProfiler(dsname=dspath, custom_label=[1], rpiformat=False)

maxpeaks = 15
minpeaks = 1
maxscore = 12
minscore = 3.5
selection = f"peaks>{minpeaks} & peaks<{maxpeaks} & score>{minscore} & score<={maxscore}"
wbpf.df = wbpf.df.query(selection)

evaluate_data(wbpf.df, model, batch_size=8, transforms_list=transforms_list_test)

Found 2725 in dataset: /home/kalfasyan/data/wingbeats/wingbeats_20211129/wingbeats_correct_dates/Suzukii_202111_SD/, and 1 label(s): ['wingbeats_correct_dates']
Label(s) changed to [1]


Creating a pandas Dataframe with file-paths, clean-scores, duration, sums of abs values, indice and labels..
Finished.


Testing..	: 100%|██████████| 213/213 [00:02<00:00, 80.86it/s]

Accuracy: 96.48
Balanced accuracy: 96.48
Confusion matrix: 
[[0.         0.        ]
 [0.03521127 0.96478873]]
1    1644
0      60
dtype: int64



/home/kalfasyan/anaconda3/envs/wbai/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1850: UserWarning: y_pred contains classes not in y_true
  warnings.warn('y_pred contains classes not in y_true')


### Testing with original controlled test set

In [13]:
test_df = pd.read_parquet('../data_created/suzmel_test.parquet')
test_dataset = DataFrameset(pd.concat([test_df.iloc[:,0], test_df.iloc[:,1]], axis=1), transform=transforms.Compose(transforms_list_test))
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=4, pin_memory=True)
_ = test_model(model,test_dataloader, test_dataset)

Testing..	: 100%|██████████| 803/803 [00:07<00:00, 109.60it/s]

Accuracy: 90.21
Balanced accuracy: 89.75
Confusion matrix: 
[[0.81614128 0.18385872]
 [0.02108056 0.97891944]]


### Testing with remote-uncontrolled test set

In [14]:
extra_df = pd.read_parquet('../data_created/suzmel_extra.parquet')
X_extra, y_extra = extra_df.iloc[:,0], extra_df.iloc[:,1]

extra_dataset = DataFrameset(pd.concat([X_extra, y_extra], axis=1), transform=transforms.Compose(transforms_list_test))
extra_dataloader = DataLoader(extra_dataset, batch_size=32, shuffle=False, num_workers=4, pin_memory=True, worker_init_fn=worker_init_fn)
_ = test_model(model,extra_dataloader, extra_dataset)

Testing..	: 100%|██████████| 712/712 [00:05<00:00, 118.97it/s]

Accuracy: 99.79
Balanced accuracy: 99.41
Confusion matrix: 
[[0.98979592 0.01020408]
 [0.00161992 0.99838008]]


# UMAP

In [15]:
%reset -f
%reload_ext autoreload
%autoreload 2
%matplotlib inline
%config Completer.use_jedi = False

In [16]:
import sys
sys.path.insert(0,"..")
from profiler import *
from utils import *
from datasets import *
from models import *
from transforms import *
import torch.nn as nn
import torch.optim as optim
import torchaudio
from torch.utils.data import Dataset, ConcatDataset
from torch.utils.data.sampler import SubsetRandomSampler
from torchvision import datasets, transforms
torchaudio.set_audio_backend('soundfile')

transforms_list_test = [Bandpass(lowcut=140, highcut=1500)]
BASE_DATACREATEDDIR

Path('/home/kalfasyan/projects/wbai/data_created')

In [17]:
model = DrosophilaNetRAW(outputs=2, dropout_p=.2)
optimizer = optim.Adam(model.parameters(), lr=0.001, eps=1e-3, amsgrad=True)
model, optimizer = load_checkpoint(f'{BASE_DATACREATEDDIR}/model_time_best.pth.tar', model, optimizer)
model = model.to('cuda', dtype=torch.float)

KeyboardInterrupt: 

In [ ]:
model = nn.Sequential(*list(model.children())[:-1])
list(model.children())[-1]

In [ ]:
dspath = "/home/kalfasyan/data/wingbeats/wingbeats_20211129/wingbeats_correct_dates/Melanogaster_202111_SD"
wbpf = WingbeatDatasetProfiler(dsname=dspath, custom_label=[2], rpiformat=False)

maxpeaks = 15
minpeaks = 1
maxscore = 12
minscore = 3.5
selection = f"peaks>{minpeaks} & peaks<{maxpeaks} & score>{minscore} & score<={maxscore}"
wbpf.df = wbpf.df.query(selection)

new_dataset = DataFrameset(pd.concat([wbpf.df.iloc[:,0], wbpf.df.iloc[:,1]], axis=1), transform=transforms.Compose(transforms_list_test))
new_dataloader = DataLoader(new_dataset, batch_size=32, shuffle=False)
out_new = get_all_preds(model, new_dataloader)
X_new_mel, y_new_mel = out_new[0].detach().cpu().numpy(), out_new[1].detach().cpu().numpy()

In [ ]:
dspath = "/home/kalfasyan/data/wingbeats/wingbeats_20211129/wingbeats_correct_dates/Suzukii_202111_SD/"
wbpf = WingbeatDatasetProfiler(dsname=dspath, custom_label=[3], rpiformat=False)

maxpeaks = 15
minpeaks = 1
maxscore = 12
minscore = 3.5
selection = f"peaks>{minpeaks} & peaks<{maxpeaks} & score>{minscore} & score<={maxscore}"
wbpf.df = wbpf.df.query(selection)

new_dataset = DataFrameset(pd.concat([wbpf.df.iloc[:,0], wbpf.df.iloc[:,1]], axis=1), transform=transforms.Compose(transforms_list_test))
new_dataloader = DataLoader(new_dataset, batch_size=32, shuffle=False)
out_new = get_all_preds(model, new_dataloader)
X_new_suz, y_new_suz = out_new[0].detach().cpu().numpy(), out_new[1].detach().cpu().numpy()

In [ ]:
test_df = pd.read_parquet('../data_created/suzmel_test.parquet')
test_dataset = DataFrameset(pd.concat([test_df.iloc[:,0], test_df.iloc[:,1]], axis=1), transform=transforms.Compose(transforms_list_test))
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=4, pin_memory=True)

out = get_all_preds(model, test_dataloader)
X_test = out[0].detach().cpu().numpy()
y_test = out[1].detach().cpu().numpy()

In [ ]:
# extra_df = pd.read_csv('../data_created/suzmel_extra.csv')
# extra_dataset = DataFrameset(pd.concat([extra_df.iloc[:,0], extra_df.iloc[:,1]], axis=1), transform=transforms.Compose(transforms_list_test))
# extra_dataloader = DataLoader(extra_dataset, batch_size=32, shuffle=False, num_workers=4, pin_memory=True, worker_init_fn=worker_init_fn)
# out_xtra = get_all_preds(model, test_dataloader)
# X_extra = out_xtra[0].detach().cpu().numpy()
# y_extra = out_xtra[1].detach().cpu().numpy()

In [ ]:
X_test_and_xtra = np.vstack((X_new_mel,X_new_suz)).squeeze()
y_test_and_xtra = np.hstack((y_new_mel,y_new_suz)).squeeze()

In [ ]:
import umap
reducer = umap.UMAP()
embedding = reducer.fit_transform(X_test_and_xtra)
embedding.shape

In [ ]:
import seaborn as sns
y_test_and_xtra.shape

In [ ]:
plt.figure(figsize=(14,14))
sns.scatterplot(x=embedding[:,0], y=embedding[:,1], hue=y_test_and_xtra, alpha=0.5, palette='colorblind')

In [ ]:
model = DrosophilaNetRAW(outputs=2, dropout_p=.2)
optimizer = optim.Adam(model.parameters(), lr=0.001, eps=1e-3, amsgrad=True)
model, optimizer = load_checkpoint(f'{BASE_DATACREATEDDIR}/model_time_best.pth.tar', model, optimizer)
model = model.to('cuda', dtype=torch.float)

test_df = pd.read_parquet('../data_created/suzmel_test.parquet')
test_dataset = DataFrameset(pd.concat([test_df.iloc[:,0], test_df.iloc[:,1]], axis=1), transform=transforms.Compose(transforms_list_test))
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=4, pin_memory=True)
_ = test_model(model,test_dataloader, test_dataset)